services:
  db:
    image: postgres
    container_name: john
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: johndb
    ports:
      - '5434:5432'
    volumes:
      - '/Users/shariar2/Documents/john-server/db_data'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
