services:
  db:
    image: postgres
    container_name: john
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: johndb
    ports:
      - '5435:5432'
    volumes:
      - '/Users/saifu/Project/john-server/db_data'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
# "C:\Users\saifu\Project\john-server"